# Generated by Django 5.0.6 on 2024-05-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
        ('stores', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='store',
        ),
        migrations.AddField(
            model_name='booking',
            name='store',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='bookings', to='stores.store'),
        ),
    ]
