# Generated by Django 5.0.6 on 2024-05-17 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_store_booking_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='kind',
        ),
    ]
