# Generated by Django 5.0.5 on 2024-05-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_booking_kind'),
        ('stores', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='store',
            field=models.ManyToManyField(blank=True, default='', related_name='bookings', to='stores.store'),
        ),
    ]
