# Generated by Django 5.0.5 on 2024-05-27 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='name',
        ),
    ]
