# Generated by Django 5.0.5 on 2024-05-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='kind_detail',
        ),
    ]
