# Generated by Django 5.0.5 on 2024-05-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_remove_store_kind_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='kind_menu',
            field=models.CharField(choices=[('음식', '음식'), ('카페', '카페'), ('기타', '기탄')], max_length=20),
        ),
    ]
