# Generated by Django 5.0.5 on 2024-05-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_alter_store_kind_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='kind_menu',
            field=models.CharField(choices=[('food', '음식'), ('cafe', '카페'), ('ect', '기타')], max_length=20),
        ),
    ]
