# Generated by Django 5.0.6 on 2024-05-15 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0002_initial'),
        ('userGroup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharedlist',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='userGroup.group'),
        ),
        migrations.AddField(
            model_name='sharedlist',
            name='store',
            field=models.ManyToManyField(related_name='share_list', to='stores.store'),
        ),
    ]
