# Generated by Django 5.0.5 on 2024-05-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userGroup', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='SharedList',
            field=models.ManyToManyField(related_name='list', to='userGroup.sharedlist'),
        ),
    ]
