# Generated by Django 5.0.5 on 2024-05-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userGroup', '0003_group_sharedlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='SharedList',
        ),
    ]
