# Generated by Django 5.0.5 on 2024-05-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_initial'),
        ('userGroup', '0005_group_user_alter_sharedlist_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedlist',
            name='store',
            field=models.ManyToManyField(related_name='share_list', to='stores.store'),
        ),
    ]
