# Generated by Django 5.0.5 on 2024-05-23 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userGroup', '0006_alter_sharedlist_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='user',
            new_name='owner',
        ),
    ]
