# Generated by Django 5.0.5 on 2024-05-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userGroup', '0007_rename_user_group_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='amenities',
            field=models.ManyToManyField(related_name='my_groups', to='userGroup.sharedlist'),
        ),
    ]
