# Generated by Django 5.0.5 on 2024-05-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userGroup', '0008_group_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='amenities',
        ),
    ]
