# Generated by Django 5.0.5 on 2024-05-25 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userGroup', '0010_group_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user',
        ),
    ]
