# Generated by Django 5.0.5 on 2024-05-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_alter_store_kind_menu'),
        ('userGroup', '0011_remove_group_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='store',
            field=models.ManyToManyField(blank=True, related_name='groups', to='stores.store'),
        ),
    ]
