# Generated by Django 5.0.5 on 2024-05-27 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userGroup', '0012_group_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='store',
        ),
    ]
